spring:
  application:
    name: resource-booking-system

  profiles:
    active: local

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jakarta.persistence.validation.mode: none
    open-in-view: false

  data:
    jpa:
      repositories:
        bootstrap-mode: default